#pragma once

#include "AIMPSDK\apiActions.h"
#include "AIMPSDK\apiPlugin.h"
#include "AIMPSDK\apiPlayer.h"
#include "AIMPSDK\apiObjects.h"
#include "AIMPSDK\apiFileManager.h"
#include "AIMPSDK\apiMessages.h"
#include "AIMPSDK\apiAlbumArt.h"
#include "AIMPSDK\apiMenu.h"
#include "AIMPSDK\apiPlaylists.h"
#include "AIMPSDK\apiMenu.h"
#include "AIMPSDK\apiMUI.h"
#include "AIMPSDK\apiMenu.h"
#include "AIMPSDK\apiOptions.h"
#include "AIMPSDK\apiAlbumArt.h"
#include "AIMPSDK\apiCore.h"
#include "AIMPSDK\apiThreading.h"

#include "Utils.h"
#include "SDK\AimpObject.h"
#include "DataConversion.h"
#include "IUnknownInterfaceImpl.h"
